CREATE DATABASE DOAN
GO
CREATE TABLE USERS
(
	USERID CHAR(10) PRIMARY KEY,
	USERNAME VARCHAR(50) NOT NULL UNIQUE,
	USERPASSWORD VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL UNIQUE,
	PROFILEPICTURE VARCHAR(255),
	
)
alter table USERS add ROLES CHAR(5) NOT NULL;
DROP TABLE USERS;
CREATE TABLE USERS
(
	USERID INT IDENTITY(1,1) PRIMARY KEY,
	USERNAME VARCHAR(50) NOT NULL UNIQUE,
	USERPASSWORD VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL UNIQUE,
	PROFILEPICTURE VARCHAR(255),
	
)

CREATE TABLE SOURCEVIDEO(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	USERID INT,
	VIDEONAME NVARCHAR(250) NOT NULL,
	VIDEOPATH NVARCHAR(500) NOT NULL,
	UPLOADDATE DATETIME DEFAULT GETDATE(),
	FILESIZE DECIMAL(5,2),
	CONSTRAINT PK_USERID FOREIGN KEY (USERID) REFERENCES USERS(USERID)
	);

CREATE TABLE SEARCHHISTORY (
	USERID INT,                                 
    SEARCHKEYWORDS NVARCHAR(255), 
    SEARCHRESULT INT,                    
    PRIMARY KEY (USERID, SEARCHKEYWORDS, SEARCHRESULT), 
    CONSTRAINT FK_UserID FOREIGN KEY (UserID) REFERENCES Users(UserID)
	);
CREATE TABLE CHAT (
	CHATID INT IDENTITY (1,1) PRIMARY KEY,
	USERID INT,
	ADMINID INT, 
	SENDERTYPE VARCHAR(10) NOT NULL CHECK (SENDERTYPE IN ('User', 'Admin')),
	MESSAGE TEXT NOT NULL,
	SENTDATE DATETIME DEFAULT GETDATE(),
	ISREAD BIT DEFAULT 0,
	CONSTRAINT FK_USERID_CHAT FOREIGN KEY (USERID) REFERENCES USERS(USERID),
	CONSTRAINT FK_ADMINID_CHAT FOREIGN KEY (ADMINID) REFERENCES USERS(USERID)
);